import { Chapter } from './lesson-learn';

// ── C PROGRAMMING (course_id = 1) ────────────────────────────────────────────
export const C_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Introduction & Output', goal: 'Understand printing',
    icon: '🖨️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'How to print in C',
        code: 'printf("Hello");', label: '👉 This prints Hello to the screen' },
      { type: 'explain', title: 'Breaking it down',
        code: 'printf("Hello");',
        points: ['printf() → the function that prints output',
                 '"Hello" → the text inside double quotes',
                 '; → every statement ends with a semicolon'] },
      { type: 'tap', question: '👉 What does printf("Hello") print?',
        options: [{ text: 'printf', correct: false },
                  { text: 'Hello',  correct: true  },
                  { text: ';',      correct: false  }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'printf("Hi");',
        options: [{ text: 'Hi',     correct: true  },
                  { text: 'Error',  correct: false  },
                  { text: 'printf', correct: false  },
                  { text: '"Hi"',   correct: false  }] },
      { type: 'fill', title: 'Complete the code to print Hello',
        blank: 'printf("___");', answer: 'Hello' },
      { type: 'rule', title: 'Remember this rule!',
        rule: 'Text must always be inside " " (double quotes)' },
      { type: 'error_fix', question: '👉 What is wrong with this code?',
        brokenCode: 'printf(Hello);',
        options: [{ text: 'Missing " " around Hello', correct: true  },
                  { text: 'Missing semicolon',         correct: false },
                  { text: 'Nothing is wrong',          correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Write the code to print "Welcome" to the screen' }
    ]
  },
  {
    chapterNum: 2, title: 'Program Structure', goal: 'Understand a full C program',
    icon: '🏗️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'A complete C program',
        code: '#include <stdio.h>\nint main() {\n  printf("Hi");\n  return 0;\n}',
        label: '👉 Every C program has this structure' },
      { type: 'explain', title: 'What each part means',
        code: '#include <stdio.h>\nint main() {\n  printf("Hi");\n  return 0;\n}',
        points: ['#include <stdio.h> → imports the print library',
                 'main() → program execution starts here',
                 '{ } → curly braces wrap the program body',
                 'return 0 → signals the program ended successfully'] },
      { type: 'tap', question: '👉 Where does the C program start?',
        options: [{ text: '#include', correct: false },
                  { text: 'main()',   correct: true  },
                  { text: 'return 0', correct: false }] },
      { type: 'mcq', question: '👉 Which line prints output?',
        code: '#include <stdio.h>\nint main() {\n  printf("Hi");\n  return 0;\n}',
        options: [{ text: '#include <stdio.h>', correct: false },
                  { text: 'int main()',         correct: false },
                  { text: 'printf("Hi")',       correct: true  },
                  { text: 'return 0',           correct: false }] },
      { type: 'error_fix', question: '👉 What is missing?',
        brokenCode: 'int main {',
        options: [{ text: 'Missing () after main', correct: true  },
                  { text: 'Missing semicolon',     correct: false },
                  { text: 'Missing return',        correct: false }] },
      { type: 'fill', title: 'Fill the function name',
        blank: 'int ___() {\n  printf("Hi");\n  return 0;\n}', answer: 'main' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a complete C program that prints "Hello World"' }
    ]
  },
  {
    chapterNum: 3, title: 'Variables', goal: 'Store values in memory',
    icon: '📦', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'How to create a variable',
        code: 'int x = 5;', label: '👉 This stores the number 5 in x' },
      { type: 'explain', title: 'Breaking it down',
        code: 'int x = 5;',
        points: ['int → data type (integer number)',
                 'x → variable name (you choose it)',
                 '5 → the value to store',
                 '= → assignment operator'] },
      { type: 'tap', question: '👉 What is the variable name in: int x = 5;',
        options: [{ text: 'int', correct: false },
                  { text: 'x',   correct: true  },
                  { text: '5',   correct: false  }] },
      { type: 'mcq', question: '👉 What is the value of y?',
        code: 'int y = 10;',
        options: [{ text: 'int', correct: false },
                  { text: 'y',   correct: false },
                  { text: '10',  correct: true  },
                  { text: '0',   correct: false }] },
      { type: 'fill', title: 'Fill in the value',
        blank: 'int z = ___;', answer: '20' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'int x == 5;',
        options: [{ text: '== should be = (use single =)', correct: true  },
                  { text: 'Missing semicolon',             correct: false },
                  { text: 'Wrong variable name',           correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a variable named "a" and assign the value 20 to it' }
    ]
  },
  {
    chapterNum: 4, title: 'Data Types', goal: 'Store different kinds of data',
    icon: '🗂️', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Three main data types',
        code: "int   a = 5;\nfloat b = 2.5;\nchar  c = 'A';",
        label: '👉 Different types for different data' },
      { type: 'explain', title: 'What each type stores',
        code: "int   a = 5;\nfloat b = 2.5;\nchar  c = 'A';",
        points: ['int → whole numbers  (5, -3, 100)',
                 'float → decimal numbers (2.5, 3.14)',
                 "char → single characters ('A', 'z', '9')"] },
      { type: 'tap', question: '👉 Which type stores decimal numbers?',
        options: [{ text: 'int',   correct: false },
                  { text: 'float', correct: true  },
                  { text: 'char',  correct: false  }] },
      { type: 'mcq', question: "👉 Which type stores a single letter like 'A'?",
        options: [{ text: 'int',    correct: false },
                  { text: 'float',  correct: false },
                  { text: 'char',   correct: true  },
                  { text: 'string', correct: false }] },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'char c = "A";',
        options: [{ text: "char uses ' ' not \" \"", correct: true  },
                  { text: 'Wrong variable name',      correct: false },
                  { text: 'Missing semicolon',        correct: false }] },
      { type: 'fill', title: 'Fill the correct type',
        blank: '___ b = 3.14;', answer: 'float' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a float variable named "price" with value 9.99' }
    ]
  },
  {
    chapterNum: 5, title: 'Input with scanf', goal: 'Read input from the user',
    icon: '⌨️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'How to take input',
        code: 'int x;\nscanf("%d", &x);', label: '👉 Reads an integer from the user' },
      { type: 'explain', title: 'Breaking it down',
        code: 'scanf("%d", &x);',
        points: ['%d → format specifier for integer',
                 '& → address-of operator (required!)',
                 'x → variable where the input is stored'] },
      { type: 'tap', question: '👉 Why is & used before x in scanf?',
        options: [{ text: 'Just decoration',         correct: false },
                  { text: 'Gives the memory address', correct: true  },
                  { text: 'Adds 1 to x',              correct: false }] },
      { type: 'mcq', question: '👉 Which format specifier reads a float?',
        options: [{ text: '%d', correct: false },
                  { text: '%f', correct: true  },
                  { text: '%c', correct: false },
                  { text: '%s', correct: false }] },
      { type: 'error_fix', question: '👉 What is missing?',
        brokenCode: 'scanf("%d", x);',
        options: [{ text: '& before x',         correct: true  },
                  { text: 'Semicolon at end',    correct: false },
                  { text: 'Quotes around x',     correct: false }] },
      { type: 'fill', title: 'Complete the scanf',
        blank: 'scanf("___", &x);', answer: '%d' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write code to read an integer from the user into a variable named "num"' }
    ]
  },
  {
    chapterNum: 6, title: 'Operators', goal: 'Perform math operations',
    icon: '➕', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Arithmetic operators in C',
        code: 'int a = 5 + 3;  // 8\nint b = 10 - 2; // 8\nint c = 4 * 2;  // 8\nint r = 10 % 3; // 1',
        label: '👉 + - * / % are arithmetic operators' },
      { type: 'explain', title: 'What each operator does',
        code: '5 + 3  = 8   (add)\n10 - 2 = 8   (subtract)\n4 * 2  = 8   (multiply)\n10 % 3 = 1   (remainder)',
        points: ['+ → addition', '- → subtraction', '* → multiplication',
                 '/ → division', '% → remainder (modulus)'] },
      { type: 'tap', question: '👉 What does % (modulus) give you?',
        options: [{ text: 'The percentage',     correct: false },
                  { text: 'The remainder',      correct: true  },
                  { text: 'The exact division', correct: false }] },
      { type: 'mcq', question: '👉 What is the value of x?',
        code: 'int x = 5 % 2;',
        options: [{ text: '0',   correct: false },
                  { text: '1',   correct: true  },
                  { text: '2',   correct: false },
                  { text: '2.5', correct: false }] },
      { type: 'fill', title: 'Fill the correct operator',
        blank: 'int x = 10 ___ 2; // result is 5', answer: '/' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'int x = 5 */ 2;',
        options: [{ text: '*/ is not a valid operator', correct: true  },
                  { text: 'Missing semicolon',          correct: false },
                  { text: 'Wrong variable type',        correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Write code to add two numbers a and b and store the result in "sum"' }
    ]
  },
  {
    chapterNum: 7, title: 'If-Else', goal: 'Make decisions in code',
    icon: '🔀', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Making decisions in C',
        code: 'if (x > 5) {\n  printf("Big");\n} else {\n  printf("Small");\n}',
        label: '👉 Runs different code based on a condition' },
      { type: 'explain', title: 'Breaking it down',
        code: 'if (x > 5) {\n  printf("Big");\n}',
        points: ['if → check a condition',
                 '(x > 5) → the condition inside parentheses',
                 '{ } → code that runs if condition is TRUE',
                 'else { } → code that runs if condition is FALSE'] },
      { type: 'tap', question: '👉 In if(x > 5), what is the condition?',
        options: [{ text: 'if',     correct: false },
                  { text: 'x > 5', correct: true  },
                  { text: 'printf', correct: false }] },
      { type: 'mcq', question: '👉 x = 10. What does this print?',
        code: 'int x = 10;\nif (x > 5) {\n  printf("Big");\n}',
        options: [{ text: 'Nothing', correct: false },
                  { text: 'Small',   correct: false },
                  { text: 'Big',     correct: true  },
                  { text: 'Error',   correct: false }] },
      { type: 'fill', title: 'Complete the condition',
        blank: 'if (x ___ 0) {\n  printf("Positive");\n}', answer: '>' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write an if-else to check if a number is even or odd using %' }
    ]
  },
  {
    chapterNum: 8, title: 'Loops', goal: 'Repeat code automatically',
    icon: '🔄', color: '#04e88d',
    steps: [
      { type: 'show', title: 'The for loop',
        code: 'for (int i = 0; i < 3; i++) {\n  printf("Hi");\n}',
        label: '👉 Prints "Hi" exactly 3 times' },
      { type: 'explain', title: 'Three parts of a for loop',
        code: 'for (start ; condition ; update)',
        points: ['int i = 0 → start: i begins at 0',
                 'i < 3 → condition: loop runs while this is true',
                 'i++ → update: i increases by 1 each time'] },
      { type: 'tap', question: '👉 How many times does this loop run?\nfor (int i = 0; i < 3; i++)',
        options: [{ text: '2', correct: false },
                  { text: '3', correct: true  },
                  { text: '4', correct: false }] },
      { type: 'mcq', question: '👉 What numbers are printed?',
        code: 'for (int i = 1; i <= 5; i++)\n  printf("%d ", i);',
        options: [{ text: '0 1 2 3 4',   correct: false },
                  { text: '1 2 3 4 5',   correct: true  },
                  { text: '1 2 3 4',     correct: false },
                  { text: '0 1 2 3 4 5', correct: false }] },
      { type: 'fill', title: 'Complete the loop limit',
        blank: 'for (int i = 0; i < ___; i++)', answer: '5' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a for loop that prints numbers 1 to 5, one per line' }
    ]
  },
  {
    chapterNum: 9, title: 'Arrays', goal: 'Store multiple values',
    icon: '📋', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Arrays store multiple values',
        code: 'int arr[3] = {1, 2, 3};', label: '👉 Stores 3 numbers in one variable' },
      { type: 'explain', title: 'How array indexing works',
        code: 'arr[0] = 1\narr[1] = 2\narr[2] = 3',
        points: ['int arr[3] → array that holds 3 integers',
                 'Index starts from 0, NOT 1',
                 'arr[0] → first element',
                 'arr[2] → last element (for size 3)'] },
      { type: 'tap', question: '👉 What is arr[0] in: int arr[3] = {1, 2, 3};',
        options: [{ text: '3', correct: false },
                  { text: '1', correct: true  },
                  { text: '2', correct: false  }] },
      { type: 'mcq', question: '👉 What is arr[1]?',
        code: 'int arr[3] = {10, 20, 30};',
        options: [{ text: '10', correct: false },
                  { text: '20', correct: true  },
                  { text: '30', correct: false },
                  { text: '0',  correct: false }] },
      { type: 'fill', title: 'Fill in the array size',
        blank: 'int arr[___] = {5, 10, 15};', answer: '3' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create an integer array with 5 elements: 1, 2, 3, 4, 5' }
    ]
  },
  {
    chapterNum: 10, title: 'Functions', goal: 'Create reusable code blocks',
    icon: '⚙️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'How to create a function',
        code: 'void greet() {\n  printf("Hi!");\n}', label: '👉 This is a function named greet' },
      { type: 'explain', title: 'Parts of a function',
        code: 'void greet() {\n  printf("Hi!");\n}',
        points: ['void → return type (void = returns nothing)',
                 'greet → the function name',
                 '() → parameters (empty = no inputs)',
                 '{ } → the function body'] },
      { type: 'tap', question: '👉 What is the function name in: void greet() { }',
        options: [{ text: 'void',  correct: false },
                  { text: 'greet', correct: true  },
                  { text: '()',    correct: false  }] },
      { type: 'mcq', question: '👉 How do you call (run) this function?',
        code: 'void greet() {\n  printf("Hi!");\n}',
        options: [{ text: 'greet',      correct: false },
                  { text: 'void greet', correct: false },
                  { text: 'greet()',    correct: true  },
                  { text: 'call greet', correct: false }] },
      { type: 'fill', title: 'Complete the function call',
        blank: 'greet___;', answer: '()' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a function called "add" that takes two int parameters and returns their sum' }
    ]
  }
];

// ── C++ PROGRAMMING (course_id = 2) ─────────────────────────────────────────
export const CPP_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Output with cout', goal: 'Print to the screen in C++',
    icon: '🖨️', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'How to print in C++',
        code: 'cout << "Hello";', label: '👉 This prints Hello to the screen' },
      { type: 'explain', title: 'Breaking it down',
        code: '#include <iostream>\nusing namespace std;\ncout << "Hello";',
        points: ['cout → character output stream',
                 '<< → insertion operator (sends text to output)',
                 '"Hello" → the text to print',
                 'using namespace std → lets you write cout instead of std::cout'] },
      { type: 'tap', question: '👉 Which operator sends data to cout?',
        options: [{ text: '>>', correct: false },
                  { text: '<<', correct: true  },
                  { text: '=',  correct: false }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'cout << "C++";',
        options: [{ text: 'cout', correct: false },
                  { text: 'C++',  correct: true  },
                  { text: '<<',   correct: false },
                  { text: 'Error',correct: false }] },
      { type: 'fill', title: 'Complete the print statement',
        blank: 'cout ___ "Hello";', answer: '<<' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'cout >> "Hello";',
        options: [{ text: '>> should be <<',   correct: true  },
                  { text: 'Missing semicolon', correct: false },
                  { text: 'Nothing is wrong',  correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Print "Welcome to C++" using cout' }
    ]
  },
  {
    chapterNum: 2, title: 'Variables & Types', goal: 'Store data in C++',
    icon: '📦', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Declaring variables in C++',
        code: 'int    age  = 20;\ndouble pi   = 3.14;\nstring name = "Abhay";',
        label: '👉 C++ has many data types' },
      { type: 'explain', title: 'Common C++ types',
        code: 'int    age  = 20;\ndouble pi   = 3.14;\nstring name = "Abhay";',
        points: ['int → whole numbers',
                 'double → decimal numbers (more precise than float)',
                 'string → text (needs #include <string>)',
                 'bool → true or false'] },
      { type: 'tap', question: '👉 Which type holds text in C++?',
        options: [{ text: 'int',    correct: false },
                  { text: 'string', correct: true  },
                  { text: 'double', correct: false }] },
      { type: 'mcq', question: '👉 What type is best for 3.14159?',
        options: [{ text: 'int',    correct: false },
                  { text: 'string', correct: false },
                  { text: 'double', correct: true  },
                  { text: 'bool',   correct: false }] },
      { type: 'fill', title: 'Fill the correct type',
        blank: '___ score = 95;', answer: 'int' },
      { type: 'final', title: 'Final Challenge',
        task: 'Declare a string variable "city" with value "Mumbai"' }
    ]
  },
  {
    chapterNum: 3, title: 'Input with cin', goal: 'Read user input in C++',
    icon: '⌨️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Reading input in C++',
        code: 'int age;\ncin >> age;', label: '👉 cin reads a value from the keyboard' },
      { type: 'explain', title: 'How cin works',
        code: 'int age;\ncin >> age;\ncout << "Age: " << age;',
        points: ['cin → character input stream',
                 '>> → extraction operator (reads input)',
                 'age → variable where input is stored',
                 'No & needed (unlike scanf in C)'] },
      { type: 'tap', question: '👉 Which operator reads data with cin?',
        options: [{ text: '<<', correct: false },
                  { text: '>>', correct: true  },
                  { text: '=',  correct: false }] },
      { type: 'mcq', question: '👉 What is the difference from C scanf?',
        options: [{ text: 'cin uses &',           correct: false },
                  { text: 'cin uses >>',           correct: true  },
                  { text: 'cin uses format codes', correct: false },
                  { text: 'They are identical',    correct: false }] },
      { type: 'fill', title: 'Complete the input',
        blank: 'cin ___ name;', answer: '>>' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read an integer "n" from the user and print it using cout' }
    ]
  },
  {
    chapterNum: 4, title: 'If-Else', goal: 'Make decisions in C++',
    icon: '🔀', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'If-else in C++',
        code: 'if (x > 10) {\n  cout << "Big";\n} else {\n  cout << "Small";\n}',
        label: '👉 Same syntax as C but with cout' },
      { type: 'explain', title: 'Comparison operators',
        code: 'x == y  (equal)\nx != y  (not equal)\nx >  y  (greater)\nx <  y  (less)\nx >= y  (greater or equal)',
        points: ['== checks equality (not =)',
                 '!= checks not equal',
                 '> < >= <= for comparisons',
                 'Condition must be in ( )'] },
      { type: 'tap', question: '👉 Which operator checks equality?',
        options: [{ text: '=',  correct: false },
                  { text: '==', correct: true  },
                  { text: '!=', correct: false }] },
      { type: 'mcq', question: '👉 x = 5. What prints?',
        code: 'if (x != 5)\n  cout << "No";\nelse\n  cout << "Yes";',
        options: [{ text: 'No',    correct: false },
                  { text: 'Yes',   correct: true  },
                  { text: 'Error', correct: false },
                  { text: 'x',     correct: false }] },
      { type: 'fill', title: 'Fill the operator',
        blank: 'if (score ___ 50)\n  cout << "Pass";', answer: '>=' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write if-else to print "Positive" if x > 0, else print "Non-positive"' }
    ]
  },
  {
    chapterNum: 5, title: 'Loops', goal: 'Repeat code in C++',
    icon: '🔄', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'For loop in C++',
        code: 'for (int i = 1; i <= 5; i++) {\n  cout << i << " ";\n}',
        label: '👉 Prints 1 2 3 4 5' },
      { type: 'explain', title: 'While loop',
        code: 'int i = 1;\nwhile (i <= 5) {\n  cout << i++;\n}',
        points: ['for → best when count is known',
                 'while → best when condition-based',
                 'i++ → shorthand for i = i + 1',
                 'Both loops need a condition to stop'] },
      { type: 'tap', question: '👉 How many times does i++ run?\nfor(int i=0; i<4; i++)',
        options: [{ text: '3', correct: false },
                  { text: '4', correct: true  },
                  { text: '5', correct: false }] },
      { type: 'mcq', question: '👉 What does this print?',
        code: 'for (int i = 0; i < 3; i++)\n  cout << i;',
        options: [{ text: '1 2 3', correct: false },
                  { text: '0 1 2', correct: true  },
                  { text: '0 1 2 3', correct: false },
                  { text: 'Error',   correct: false }] },
      { type: 'fill', title: 'Complete the loop',
        blank: 'for (int i = 0; ___ ; i++)', answer: 'i < 5' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a loop that prints even numbers from 2 to 10' }
    ]
  },
  {
    chapterNum: 6, title: 'Functions', goal: 'Write reusable C++ functions',
    icon: '⚙️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Functions in C++',
        code: 'int add(int a, int b) {\n  return a + b;\n}', label: '👉 Returns the sum of two numbers' },
      { type: 'explain', title: 'Parts of a function',
        code: 'int add(int a, int b) {\n  return a + b;\n}',
        points: ['int → return type (function gives back an int)',
                 'add → function name',
                 'int a, int b → parameters with types',
                 'return → sends the result back'] },
      { type: 'tap', question: '👉 What does "return" do?',
        options: [{ text: 'Ends the program',   correct: false },
                  { text: 'Sends back a value', correct: true  },
                  { text: 'Prints output',       correct: false }] },
      { type: 'mcq', question: '👉 What is the return type of: void greet() { }',
        options: [{ text: 'int',  correct: false },
                  { text: 'void', correct: true  },
                  { text: 'bool', correct: false },
                  { text: 'none', correct: false }] },
      { type: 'fill', title: 'Fill the return type',
        blank: '___ square(int n) { return n * n; }', answer: 'int' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a function "multiply" that takes two ints and returns their product' }
    ]
  },
  {
    chapterNum: 7, title: 'Classes & Objects', goal: 'Intro to OOP in C++',
    icon: '🏛️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Your first class',
        code: 'class Car {\npublic:\n  string brand;\n  int speed;\n};', label: '👉 A class is a blueprint for objects' },
      { type: 'explain', title: 'Class vs Object',
        code: 'Car myCar;\nmyCar.brand = "Toyota";\nmyCar.speed = 120;',
        points: ['class → the blueprint/template',
                 'object → an instance of the class',
                 'public → members accessible from outside',
                 '. (dot) → access an object\'s member'] },
      { type: 'tap', question: '👉 What is an object?',
        options: [{ text: 'The blueprint',        correct: false },
                  { text: 'An instance of a class', correct: true  },
                  { text: 'A function',             correct: false }] },
      { type: 'mcq', question: '👉 How do you access myCar\'s speed?',
        options: [{ text: 'Car.speed',    correct: false },
                  { text: 'myCar->speed', correct: false },
                  { text: 'myCar.speed',  correct: true  },
                  { text: 'speed.myCar',  correct: false }] },
      { type: 'fill', title: 'Fill in the access specifier',
        blank: 'class Dog {\n___:\n  string name;\n};', answer: 'public' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a class "Student" with public members: name (string) and grade (int)' }
    ]
  },
  {
    chapterNum: 8, title: 'Arrays & Vectors', goal: 'Store collections in C++',
    icon: '📋', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Arrays and vectors',
        code: 'int arr[3] = {1, 2, 3};\nvector<int> v = {1, 2, 3};',
        label: '👉 vector is a modern C++ alternative to arrays' },
      { type: 'explain', title: 'Vector advantages',
        code: 'vector<int> v;\nv.push_back(10);\nv.push_back(20);\ncout << v.size();',
        points: ['vector can grow dynamically (no fixed size)',
                 'push_back() adds to the end',
                 'size() returns number of elements',
                 'Access same as array: v[0], v[1]'] },
      { type: 'tap', question: '👉 What does push_back() do?',
        options: [{ text: 'Removes last element', correct: false },
                  { text: 'Adds to the end',      correct: true  },
                  { text: 'Sorts the vector',      correct: false }] },
      { type: 'mcq', question: '👉 What is v.size() after: vector<int> v = {5,10,15};',
        options: [{ text: '0', correct: false },
                  { text: '2', correct: false },
                  { text: '3', correct: true  },
                  { text: '5', correct: false }] },
      { type: 'fill', title: 'Add element to vector',
        blank: 'v.___( 42 );', answer: 'push_back' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a vector of ints, add 3 numbers, and print the size' }
    ]
  },
  {
    chapterNum: 9, title: 'Inheritance', goal: 'Extend classes in C++',
    icon: '🧬', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Inheriting a class',
        code: 'class Animal {\npublic:\n  void eat() { cout << "Eating"; }\n};\n\nclass Dog : public Animal {\npublic:\n  void bark() { cout << "Woof"; }\n};',
        label: '👉 Dog inherits eat() from Animal' },
      { type: 'explain', title: 'How inheritance works',
        code: 'Dog d;\nd.eat();  // from Animal\nd.bark(); // from Dog',
        points: [': public Animal → inherit from Animal',
                 'Child gets all public members of parent',
                 'Child can add its own members',
                 'This avoids code duplication'] },
      { type: 'tap', question: '👉 What does Dog inherit from Animal?',
        options: [{ text: 'Nothing',     correct: false },
                  { text: 'eat()',       correct: true  },
                  { text: 'Only names', correct: false }] },
      { type: 'mcq', question: '👉 Which syntax means "Dog inherits Animal"?',
        options: [{ text: 'class Dog extends Animal',    correct: false },
                  { text: 'class Dog : public Animal',   correct: true  },
                  { text: 'class Dog inherits Animal',   correct: false },
                  { text: 'Dog.inherit(Animal)',          correct: false }] },
      { type: 'fill', title: 'Complete the inheritance',
        blank: 'class Cat ___ Animal {', answer: ': public' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a Shape class with area() method, then inherit a Circle class from it' }
    ]
  },
  {
    chapterNum: 10, title: 'Pointers', goal: 'Understand memory addresses',
    icon: '🔗', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'What is a pointer?',
        code: 'int x = 10;\nint* p = &x;\ncout << *p; // prints 10',
        label: '👉 p stores the memory address of x' },
      { type: 'explain', title: 'Pointer operators',
        code: 'int* p = &x;  // & = address of\ncout << p;    // prints address\ncout << *p;   // * = dereference = value',
        points: ['& → gives the memory address of a variable',
                 '* (in declaration) → declares a pointer',
                 '* (in use) → dereferences: gets the value',
                 'int* p → pointer to an integer'] },
      { type: 'tap', question: '👉 What does * do when used on a pointer?',
        options: [{ text: 'Multiplies values',      correct: false },
                  { text: 'Gets the stored value',  correct: true  },
                  { text: 'Gets the address',        correct: false }] },
      { type: 'mcq', question: '👉 int x=5; int* p=&x; What is *p?',
        options: [{ text: 'Address of x', correct: false },
                  { text: '5',            correct: true  },
                  { text: 'p',            correct: false },
                  { text: '0',            correct: false }] },
      { type: 'fill', title: 'Complete the pointer declaration',
        blank: 'int___ p = &x;', answer: '*' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a variable y=20, a pointer to it, and print the value via the pointer' }
    ]
  }
];

// ── JAVA (course_id = 3) ─────────────────────────────────────────────────────
export const JAVA_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Output', goal: 'Print to the screen in Java',
    icon: '🖨️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Printing in Java',
        code: 'System.out.println("Hello");', label: '👉 println prints and moves to next line' },
      { type: 'explain', title: 'Breaking it down',
        code: 'System.out.println("Hello");',
        points: ['System → the Java system class',
                 'out → the output stream',
                 'println() → print + newline',
                 'print() → prints without newline'] },
      { type: 'tap', question: '👉 What does println add after printing?',
        options: [{ text: 'A space',   correct: false },
                  { text: 'A newline', correct: true  },
                  { text: 'Nothing',   correct: false }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'System.out.println("Java");',
        options: [{ text: 'System', correct: false },
                  { text: 'Java',   correct: true  },
                  { text: 'println',correct: false },
                  { text: 'Error',  correct: false }] },
      { type: 'fill', title: 'Complete the print statement',
        blank: 'System.out._____("Hello");', answer: 'println' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'system.out.println("Hi");',
        options: [{ text: '"system" should be "System" (capital S)', correct: true  },
                  { text: 'Missing semicolon',                        correct: false },
                  { text: 'Nothing is wrong',                         correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Print "Hello Java" using the correct Java syntax' }
    ]
  },
  {
    chapterNum: 2, title: 'Variables', goal: 'Store data in Java',
    icon: '📦', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Variables in Java',
        code: 'int age    = 20;\nString name = "Abhay";\ndouble gpa  = 9.5;',
        label: '👉 Java is strongly typed' },
      { type: 'explain', title: 'Java data types',
        code: 'int    → whole numbers\nString → text (capital S!)\ndouble → decimals\nboolean→ true/false',
        points: ['int → integers (−2B to 2B)',
                 'String → text, capital S, in double quotes',
                 'double → decimal numbers',
                 'boolean → true or false (no quotes)'] },
      { type: 'tap', question: '👉 How is String different in Java vs other types?',
        options: [{ text: 'It uses single quotes',     correct: false },
                  { text: 'It starts with capital S',  correct: true  },
                  { text: 'It does not need a type',   correct: false }] },
      { type: 'mcq', question: '👉 Which is correct for text in Java?',
        options: [{ text: 'string name = "Ali";', correct: false },
                  { text: 'String name = "Ali";', correct: true  },
                  { text: "String name = 'Ali';", correct: false },
                  { text: 'TEXT name = "Ali";',   correct: false }] },
      { type: 'fill', title: 'Fill the type',
        blank: '___ isActive = true;', answer: 'boolean' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a String variable "language" with value "Java" and print it' }
    ]
  },
  {
    chapterNum: 3, title: 'Input (Scanner)', goal: 'Read user input in Java',
    icon: '⌨️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Reading input with Scanner',
        code: 'Scanner sc = new Scanner(System.in);\nint n = sc.nextInt();',
        label: '👉 Scanner reads input from the keyboard' },
      { type: 'explain', title: 'Scanner methods',
        code: 'sc.nextInt()    → reads an integer\nsc.nextDouble() → reads a decimal\nsc.next()       → reads a word\nsc.nextLine()   → reads a full line',
        points: ['Import: import java.util.Scanner;',
                 'Create: new Scanner(System.in)',
                 'nextInt() → reads whole number',
                 'nextLine() → reads full sentence'] },
      { type: 'tap', question: '👉 Which method reads a full line of text?',
        options: [{ text: 'next()',     correct: false },
                  { text: 'nextLine()', correct: true  },
                  { text: 'nextInt()',  correct: false }] },
      { type: 'mcq', question: '👉 What is needed to use Scanner?',
        options: [{ text: 'import java.lang.Scanner',  correct: false },
                  { text: 'import java.util.Scanner',  correct: true  },
                  { text: 'include Scanner',           correct: false },
                  { text: 'Nothing extra needed',      correct: false }] },
      { type: 'fill', title: 'Read an integer',
        blank: 'int x = sc.___();', answer: 'nextInt' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read a name using Scanner and print "Hello, [name]"' }
    ]
  },
  {
    chapterNum: 4, title: 'If-Else', goal: 'Decision making in Java',
    icon: '🔀', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'If-else in Java',
        code: 'if (score >= 50) {\n  System.out.println("Pass");\n} else {\n  System.out.println("Fail");\n}',
        label: '👉 Same structure as C/C++' },
      { type: 'explain', title: 'String comparison in Java',
        code: '// WRONG:\nif (name == "Abhay")\n\n// CORRECT:\nif (name.equals("Abhay"))',
        points: ['== works for int, double, boolean',
                 'For String: use .equals() not ==',
                 '== on Strings compares memory address',
                 '.equalsIgnoreCase() ignores caps'] },
      { type: 'tap', question: '👉 How to compare Strings in Java?',
        options: [{ text: '==',      correct: false },
                  { text: '.equals()',correct: true  },
                  { text: '===',      correct: false }] },
      { type: 'mcq', question: '👉 score = 75. What prints?',
        code: 'if (score > 90)\n  System.out.println("A");\nelse if (score > 60)\n  System.out.println("B");\nelse\n  System.out.println("C");',
        options: [{ text: 'A', correct: false },
                  { text: 'B', correct: true  },
                  { text: 'C', correct: false },
                  { text: 'Error', correct: false }] },
      { type: 'fill', title: 'Fill the string comparison',
        blank: 'if (city.___("Delhi"))', answer: 'equals' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read a number and print if it is positive, negative, or zero' }
    ]
  },
  {
    chapterNum: 5, title: 'Loops', goal: 'Repeat code in Java',
    icon: '🔄', color: '#ffc800',
    steps: [
      { type: 'show', title: 'For loop in Java',
        code: 'for (int i = 1; i <= 5; i++) {\n  System.out.println(i);\n}',
        label: '👉 Prints 1 through 5' },
      { type: 'explain', title: 'Enhanced for loop',
        code: 'int[] nums = {10, 20, 30};\nfor (int n : nums) {\n  System.out.println(n);\n}',
        points: ['for (int n : nums) → "for each n in nums"',
                 'Enhanced for = cleaner iteration over arrays',
                 'Cannot use index with enhanced for',
                 'Regular for needed when you need the index'] },
      { type: 'tap', question: '👉 What does "for (int n : nums)" mean?',
        options: [{ text: 'Loop n times',          correct: false },
                  { text: 'For each element in nums', correct: true  },
                  { text: 'Loop from n to nums',    correct: false }] },
      { type: 'mcq', question: '👉 How many times does this loop run?',
        code: 'for (int i = 0; i < 4; i++)',
        options: [{ text: '3', correct: false },
                  { text: '4', correct: true  },
                  { text: '5', correct: false },
                  { text: '0', correct: false }] },
      { type: 'fill', title: 'Complete the enhanced for',
        blank: 'for (int x ___ arr)', answer: ':' },
      { type: 'final', title: 'Final Challenge',
        task: 'Print multiplication table of 5 (5×1 to 5×10) using a loop' }
    ]
  },
  {
    chapterNum: 6, title: 'Methods', goal: 'Write reusable Java methods',
    icon: '⚙️', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Methods in Java',
        code: 'static int add(int a, int b) {\n  return a + b;\n}',
        label: '👉 static lets you call it without an object' },
      { type: 'explain', title: 'Method structure',
        code: 'static int add(int a, int b) {\n  return a + b;\n}',
        points: ['static → call directly: add(2,3)',
                 'int → return type',
                 'add → method name',
                 '(int a, int b) → parameters'] },
      { type: 'tap', question: '👉 Why use static on a method?',
        options: [{ text: 'Makes it faster',             correct: false },
                  { text: 'Call without creating object', correct: true  },
                  { text: 'Makes it private',            correct: false }] },
      { type: 'mcq', question: '👉 What is the return type of: static void greet() {}',
        options: [{ text: 'static', correct: false },
                  { text: 'void',   correct: true  },
                  { text: 'greet',  correct: false },
                  { text: 'int',    correct: false }] },
      { type: 'fill', title: 'Fill the return type',
        blank: 'static ___ square(int n) { return n*n; }', answer: 'int' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a method "isEven" that takes an int and returns true if even' }
    ]
  },
  {
    chapterNum: 7, title: 'Classes & Objects', goal: 'OOP in Java',
    icon: '🏛️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Class in Java',
        code: 'class Car {\n  String brand;\n  int speed;\n\n  void drive() {\n    System.out.println("Driving " + brand);\n  }\n}',
        label: '👉 Class groups data and behavior' },
      { type: 'explain', title: 'Creating objects',
        code: 'Car c = new Car();\nc.brand = "BMW";\nc.speed = 200;\nc.drive();',
        points: ['new Car() → creates an object in memory',
                 'c.brand → access field with dot',
                 'c.drive() → call method with dot',
                 'Each object has its own copy of fields'] },
      { type: 'tap', question: '👉 How do you create an object in Java?',
        options: [{ text: 'Car c = Car()',     correct: false },
                  { text: 'Car c = new Car()', correct: true  },
                  { text: 'create Car c',       correct: false }] },
      { type: 'mcq', question: '👉 What does + do between String and int in Java?',
        options: [{ text: 'Addition',          correct: false },
                  { text: 'String concatenation', correct: true  },
                  { text: 'Error',              correct: false },
                  { text: 'Nothing',            correct: false }] },
      { type: 'fill', title: 'Create an object',
        blank: 'Dog d = ___ Dog();', answer: 'new' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a Person class with name and age fields, then create an object and print them' }
    ]
  },
  {
    chapterNum: 8, title: 'Arrays', goal: 'Store collections in Java',
    icon: '📋', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Arrays in Java',
        code: 'int[] nums = {10, 20, 30};\nSystem.out.println(nums[0]); // 10',
        label: '👉 [] after type declares an array' },
      { type: 'explain', title: 'Array properties',
        code: 'int[] arr = new int[5];\narr[0] = 1;\nSystem.out.println(arr.length);',
        points: ['int[] arr → array of ints',
                 'new int[5] → creates array of size 5',
                 'arr.length → number of elements',
                 'Index starts at 0'] },
      { type: 'tap', question: '👉 How do you get array length in Java?',
        options: [{ text: 'arr.size()',   correct: false },
                  { text: 'arr.length',   correct: true  },
                  { text: 'length(arr)',  correct: false }] },
      { type: 'mcq', question: '👉 What is nums[2]?',
        code: 'int[] nums = {5, 10, 15, 20};',
        options: [{ text: '5',  correct: false },
                  { text: '10', correct: false },
                  { text: '15', correct: true  },
                  { text: '20', correct: false }] },
      { type: 'fill', title: 'Declare an int array',
        blank: '___ scores = {90, 80, 70};', answer: 'int[]' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create an array of 5 marks, loop through it, and print the sum' }
    ]
  },
  {
    chapterNum: 9, title: 'Inheritance', goal: 'Extend classes in Java',
    icon: '🧬', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Inheritance in Java',
        code: 'class Animal {\n  void eat() { System.out.println("Eating"); }\n}\n\nclass Dog extends Animal {\n  void bark() { System.out.println("Woof!"); }\n}',
        label: '👉 Dog inherits eat() from Animal' },
      { type: 'explain', title: 'extends keyword',
        code: 'Dog d = new Dog();\nd.eat();  // inherited\nd.bark(); // own method',
        points: ['extends → keyword for inheritance in Java',
                 'Child class gets all public/protected methods',
                 'super() → calls parent constructor',
                 '@Override → overrides a parent method'] },
      { type: 'tap', question: '👉 Which keyword is used for inheritance in Java?',
        options: [{ text: 'inherits', correct: false },
                  { text: 'extends',  correct: true  },
                  { text: ':',        correct: false }] },
      { type: 'mcq', question: '👉 Can a Java class extend multiple classes?',
        options: [{ text: 'Yes, always',              correct: false },
                  { text: 'No, only one parent class', correct: true  },
                  { text: 'Yes, with extends[]',       correct: false },
                  { text: 'Only if they are abstract', correct: false }] },
      { type: 'fill', title: 'Complete the inheritance',
        blank: 'class Cat ___ Animal {', answer: 'extends' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create Vehicle class with move(), then Car class extending Vehicle with honk()' }
    ]
  },
  {
    chapterNum: 10, title: 'Interfaces', goal: 'Understand Java interfaces',
    icon: '🔌', color: '#ffc800',
    steps: [
      { type: 'show', title: 'What is an interface?',
        code: 'interface Drawable {\n  void draw();\n}\n\nclass Circle implements Drawable {\n  public void draw() {\n    System.out.println("Drawing circle");\n  }\n}',
        label: '👉 Interface defines a contract' },
      { type: 'explain', title: 'Interface vs Class',
        code: 'interface Shape {\n  double area(); // no body\n}',
        points: ['Interface has no method bodies (only signatures)',
                 'implements → class fulfills the interface',
                 'A class can implement MULTIPLE interfaces',
                 'All interface methods must be public'] },
      { type: 'tap', question: '👉 What keyword does a class use to implement an interface?',
        options: [{ text: 'extends',    correct: false },
                  { text: 'implements', correct: true  },
                  { text: 'uses',       correct: false }] },
      { type: 'mcq', question: '👉 Can a class implement multiple interfaces?',
        options: [{ text: 'No',         correct: false },
                  { text: 'Yes',        correct: true  },
                  { text: 'Only 2',     correct: false },
                  { text: 'Only abstract ones', correct: false }] },
      { type: 'fill', title: 'Complete the class declaration',
        blank: 'class Square ___ Shape {', answer: 'implements' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create an interface "Greetable" with greet() method, then implement it in a Person class' }
    ]
  }
];

// ── JAVASCRIPT (course_id = 5) ───────────────────────────────────────────────
export const JS_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Output', goal: 'Print output in JavaScript',
    icon: '🖨️', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Output in JavaScript',
        code: 'console.log("Hello World");', label: '👉 console.log prints to the browser console' },
      { type: 'explain', title: 'Ways to output',
        code: 'console.log("debug output");\ndocument.write("on the page");\nalert("popup message");',
        points: ['console.log() → developer console (F12)',
                 'document.write() → writes to the webpage',
                 'alert() → shows a popup dialog',
                 'console.log is used most in coding'] },
      { type: 'tap', question: '👉 Which is best for debugging?',
        options: [{ text: 'document.write()', correct: false },
                  { text: 'console.log()',    correct: true  },
                  { text: 'alert()',          correct: false }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'console.log(2 + 3);',
        options: [{ text: '"2 + 3"', correct: false },
                  { text: '5',       correct: true  },
                  { text: '23',      correct: false },
                  { text: 'Error',   correct: false }] },
      { type: 'fill', title: 'Complete the log',
        blank: 'console.___("Hello");', answer: 'log' },
      { type: 'final', title: 'Final Challenge',
        task: 'Print "JavaScript is fun!" to the console' }
    ]
  },
  {
    chapterNum: 2, title: 'Variables', goal: 'Store data in JavaScript',
    icon: '📦', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Variables in JavaScript',
        code: 'let name   = "Abhay";\nconst PI   = 3.14;\nvar old    = "avoid";',
        label: '👉 Use let and const (not var)' },
      { type: 'explain', title: 'let vs const vs var',
        code: 'let x = 5;     // can change\nconst Y = 10;  // cannot change\nvar z = 15;    // old way, avoid',
        points: ['let → reassignable variable',
                 'const → constant, cannot be reassigned',
                 'var → old style, has scoping issues, avoid',
                 'JavaScript is loosely typed (no need to declare type)'] },
      { type: 'tap', question: '👉 Which keyword creates a constant?',
        options: [{ text: 'let',   correct: false },
                  { text: 'const', correct: true  },
                  { text: 'var',   correct: false }] },
      { type: 'mcq', question: '👉 What happens if you try to reassign a const?',
        options: [{ text: 'It works fine',    correct: false },
                  { text: 'TypeError (error)', correct: true  },
                  { text: 'It becomes null',   correct: false },
                  { text: 'It becomes 0',      correct: false }] },
      { type: 'fill', title: 'Declare a constant PI',
        blank: '___ PI = 3.14;', answer: 'const' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a let variable "score" = 100 and a const "name" = "Player1", then log both' }
    ]
  },
  {
    chapterNum: 3, title: 'Data Types', goal: 'Understand JS types',
    icon: '🗂️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'JavaScript data types',
        code: 'let num  = 42;\nlet text = "hello";\nlet flag = true;\nlet empty = null;',
        label: '👉 JS has 7 primitive types' },
      { type: 'explain', title: 'Type coercion',
        code: 'console.log("5" + 2);   // "52" (string)\nconsole.log("5" - 2);   // 3  (number)\nconsole.log(typeof "hi"); // "string"',
        points: ['+ with string = concatenation',
                 '- always converts to number',
                 'typeof → reveals the type',
                 'undefined = declared but no value'] },
      { type: 'tap', question: '👉 What is "5" + 2 in JavaScript?',
        options: [{ text: '7',    correct: false },
                  { text: '"52"', correct: true  },
                  { text: 'Error',correct: false }] },
      { type: 'mcq', question: '👉 What does typeof 42 return?',
        options: [{ text: '"int"',    correct: false },
                  { text: '"number"', correct: true  },
                  { text: '"42"',     correct: false },
                  { text: 'undefined',correct: false }] },
      { type: 'fill', title: 'Get the type',
        blank: 'console.log(___ "hello");', answer: 'typeof' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create variables of type number, string, and boolean, then log each with typeof' }
    ]
  },
  {
    chapterNum: 4, title: 'Functions', goal: 'Write functions in JavaScript',
    icon: '⚙️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Functions in JavaScript',
        code: 'function greet(name) {\n  return "Hello, " + name;\n}\nconsole.log(greet("Abhay"));',
        label: '👉 Functions are defined with the function keyword' },
      { type: 'explain', title: 'Arrow functions',
        code: '// Regular:\nfunction add(a, b) { return a + b; }\n\n// Arrow:\nconst add = (a, b) => a + b;',
        points: ['Arrow functions: shorter syntax',
                 '=> (fat arrow) replaces function keyword',
                 'Single expression: no need for return',
                 'Arrow functions are very common in modern JS'] },
      { type: 'tap', question: '👉 What is the arrow function symbol?',
        options: [{ text: '->', correct: false },
                  { text: '=>', correct: true  },
                  { text: ':',  correct: false }] },
      { type: 'mcq', question: '👉 What does this arrow function return?',
        code: 'const double = x => x * 2;\nconsole.log(double(5));',
        options: [{ text: '5',  correct: false },
                  { text: '10', correct: true  },
                  { text: '2',  correct: false },
                  { text: 'undefined', correct: false }] },
      { type: 'fill', title: 'Convert to arrow function',
        blank: 'const square = x ___ x * x;', answer: '=>' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write an arrow function "max" that takes two numbers and returns the larger one' }
    ]
  },
  {
    chapterNum: 5, title: 'Arrays', goal: 'Work with arrays in JS',
    icon: '📋', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Arrays in JavaScript',
        code: 'const fruits = ["apple", "mango", "banana"];\nconsole.log(fruits[0]); // apple',
        label: '👉 Arrays use square brackets, index starts at 0' },
      { type: 'explain', title: 'Array methods',
        code: 'fruits.push("grape");     // add to end\nfruits.pop();             // remove last\nfruits.length;            // size\nfruits.includes("mango"); // true/false',
        points: ['push() → add to end',
                 'pop() → remove last element',
                 '.length → number of items',
                 'includes() → check if item exists'] },
      { type: 'tap', question: '👉 Which method adds to end of array?',
        options: [{ text: 'add()',    correct: false },
                  { text: 'push()',   correct: true  },
                  { text: 'append()', correct: false }] },
      { type: 'mcq', question: '👉 What is fruits.length?',
        code: 'const fruits = ["a", "b", "c", "d"];',
        options: [{ text: '3', correct: false },
                  { text: '4', correct: true  },
                  { text: '0', correct: false },
                  { text: 'undefined', correct: false }] },
      { type: 'fill', title: 'Add an element',
        blank: 'arr.___("newItem");', answer: 'push' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create an array of 3 numbers, push a 4th, and log the sum using a loop' }
    ]
  },
  {
    chapterNum: 6, title: 'Objects', goal: 'Use JavaScript objects',
    icon: '📑', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Objects in JavaScript',
        code: 'const person = {\n  name: "Abhay",\n  age: 20,\n  greet() { return "Hi!"; }\n};',
        label: '👉 Objects store key-value pairs' },
      { type: 'explain', title: 'Accessing object properties',
        code: 'person.name         // "Abhay" (dot notation)\nperson["age"]       // 20 (bracket notation)\nperson.greet()      // "Hi!" (method call)',
        points: ['Dot notation: obj.key',
                 'Bracket notation: obj["key"]',
                 'Methods are functions inside objects',
                 'Objects can contain arrays and other objects'] },
      { type: 'tap', question: '👉 What are objects made of?',
        options: [{ text: 'Indexed elements', correct: false },
                  { text: 'Key-value pairs',  correct: true  },
                  { text: 'Only numbers',      correct: false }] },
      { type: 'mcq', question: '👉 How do you get "Abhay" from person?',
        code: 'const person = { name: "Abhay", age: 20 };',
        options: [{ text: 'person[0]',    correct: false },
                  { text: 'person.name',  correct: true  },
                  { text: 'name.person',  correct: false },
                  { text: 'person->name', correct: false }] },
      { type: 'fill', title: 'Access the age property',
        blank: 'console.log(person.___);', answer: 'age' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a "car" object with brand, year, and a method that returns the brand' }
    ]
  },
  {
    chapterNum: 7, title: 'DOM Basics', goal: 'Manipulate the webpage',
    icon: '🌐', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Selecting HTML elements',
        code: 'document.getElementById("btn");\ndocument.querySelector(".card");\ndocument.querySelectorAll("p");',
        label: '👉 DOM lets JS control the webpage' },
      { type: 'explain', title: 'Changing elements',
        code: 'const el = document.getElementById("title");\nel.textContent = "New Title";\nel.style.color = "red";\nel.classList.add("active");',
        points: ['textContent → change the text',
                 'style.color → change CSS style',
                 'classList.add() → add a CSS class',
                 'innerHTML → set HTML content (careful with XSS)'] },
      { type: 'tap', question: '👉 Which selects element by id?',
        options: [{ text: 'querySelector()',   correct: false },
                  { text: 'getElementById()',  correct: true  },
                  { text: 'getElement()',       correct: false }] },
      { type: 'mcq', question: '👉 How do you change text of an element?',
        options: [{ text: 'el.text = "x"',        correct: false },
                  { text: 'el.textContent = "x"',  correct: true  },
                  { text: 'el.value = "x"',         correct: false },
                  { text: 'el.innerText() = "x"',   correct: false }] },
      { type: 'fill', title: 'Change text',
        blank: 'el.___ = "Hello";', answer: 'textContent' },
      { type: 'final', title: 'Final Challenge',
        task: 'Select an element with id "output" and set its text to "JavaScript rocks!"' }
    ]
  },
  {
    chapterNum: 8, title: 'Events', goal: 'React to user actions',
    icon: '👆', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Adding event listeners',
        code: 'btn.addEventListener("click", function() {\n  console.log("Clicked!");\n});',
        label: '👉 addEventListener waits for user action' },
      { type: 'explain', title: 'Common events',
        code: '"click"     → mouse click\n"mouseover" → hover\n"keydown"   → key pressed\n"submit"    → form submitted\n"load"      → page loaded',
        points: ['addEventListener(event, callback)',
                 'Callback runs when event occurs',
                 'event.target → the element that was clicked',
                 'event.preventDefault() → stops default behavior'] },
      { type: 'tap', question: '👉 What is the first argument to addEventListener?',
        options: [{ text: 'The callback function', correct: false },
                  { text: 'The event name (string)', correct: true  },
                  { text: 'The element',              correct: false }] },
      { type: 'mcq', question: '👉 Which event fires when user types a key?',
        options: [{ text: 'click',   correct: false },
                  { text: 'keydown', correct: true  },
                  { text: 'focus',   correct: false },
                  { text: 'load',    correct: false }] },
      { type: 'fill', title: 'Add a click listener',
        blank: 'btn.___("click", () => alert("Hi"));', answer: 'addEventListener' },
      { type: 'final', title: 'Final Challenge',
        task: 'Add a click listener to a button that changes its text to "Clicked!"' }
    ]
  },
  {
    chapterNum: 9, title: 'Promises & Async', goal: 'Handle async code in JS',
    icon: '⏳', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Async/Await',
        code: 'async function getData() {\n  const res = await fetch(url);\n  const data = await res.json();\n  console.log(data);\n}',
        label: '👉 async/await handles asynchronous operations' },
      { type: 'explain', title: 'Why async code exists',
        code: '// Without async: code continues before data arrives\n// With await: code waits for the operation\nconst data = await fetch("/api/users");',
        points: ['async function → can use await inside',
                 'await → pauses until Promise resolves',
                 'fetch() → makes HTTP requests',
                 'Avoid "callback hell" with async/await'] },
      { type: 'tap', question: '👉 What does await do?',
        options: [{ text: 'Delays 1 second',          correct: false },
                  { text: 'Waits for Promise to resolve', correct: true  },
                  { text: 'Creates a new thread',     correct: false }] },
      { type: 'mcq', question: '👉 To use await, the function must be declared as?',
        options: [{ text: 'sync',   correct: false },
                  { text: 'async',  correct: true  },
                  { text: 'defer',  correct: false },
                  { text: 'await',  correct: false }] },
      { type: 'fill', title: 'Complete the async function',
        blank: '___ function loadData() { }', answer: 'async' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write an async function that fetches data from a URL and logs the response' }
    ]
  },
  {
    chapterNum: 10, title: 'Classes (ES6)', goal: 'OOP in modern JavaScript',
    icon: '🏛️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Classes in JavaScript',
        code: 'class Animal {\n  constructor(name) {\n    this.name = name;\n  }\n  speak() {\n    console.log(this.name + " speaks");\n  }\n}',
        label: '👉 ES6 classes are syntactic sugar over prototypes' },
      { type: 'explain', title: 'Inheritance in JS classes',
        code: 'class Dog extends Animal {\n  bark() { console.log("Woof!"); }\n}\nconst d = new Dog("Rex");\nd.speak(); // from Animal\nd.bark();  // from Dog',
        points: ['constructor() → runs when object is created',
                 'this → refers to the current object',
                 'extends → inherit from another class',
                 'super() → call parent constructor'] },
      { type: 'tap', question: '👉 What runs automatically when you use new Dog()?',
        options: [{ text: 'speak()',      correct: false },
                  { text: 'constructor()', correct: true  },
                  { text: 'init()',        correct: false }] },
      { type: 'mcq', question: '👉 How do you inherit in JS?',
        options: [{ text: 'class Dog implements Animal',  correct: false },
                  { text: 'class Dog extends Animal',     correct: true  },
                  { text: 'class Dog : Animal',           correct: false },
                  { text: 'Dog.inherit(Animal)',          correct: false }] },
      { type: 'fill', title: 'Access instance property',
        blank: 'class Car {\n  constructor(brand) { ___.brand = brand; }\n}', answer: 'this' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a Vehicle class with a constructor and speed field, then extend it with a Bike class' }
    ]
  }
];

// ── PYTHON (course_id = 6) ───────────────────────────────────────────────────
export const PYTHON_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Output with print()', goal: 'Print output in Python',
    icon: '🖨️', color: '#3572A5',
    steps: [
      { type: 'show', title: 'Printing in Python',
        code: 'print("Hello World")', label: '👉 Python uses print() — no semicolons!' },
      { type: 'explain', title: 'Python print features',
        code: 'print("Hello")           # one value\nprint("Hi", "World")    # two values\nprint("Sum:", 5 + 3)    # text + math',
        points: ['print() → built-in output function',
                 'Multiple values separated by comma',
                 'No semicolons needed in Python',
                 '# starts a comment'] },
      { type: 'tap', question: '👉 How do you start a comment in Python?',
        options: [{ text: '//',  correct: false },
                  { text: '#',   correct: true  },
                  { text: '/*',  correct: false }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'print(2 + 3)',
        options: [{ text: '"2 + 3"', correct: false },
                  { text: '5',       correct: true  },
                  { text: '23',      correct: false },
                  { text: 'Error',   correct: false }] },
      { type: 'fill', title: 'Complete the print',
        blank: '___("Hello Python")', answer: 'print' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'Print("Hello")',
        options: [{ text: '"Print" should be "print" (lowercase)', correct: true  },
                  { text: 'Missing semicolon',                      correct: false },
                  { text: 'Nothing is wrong',                       correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Print your name and age on the same line using print()' }
    ]
  },
  {
    chapterNum: 2, title: 'Variables', goal: 'Store data in Python',
    icon: '📦', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Variables in Python',
        code: 'name = "Abhay"\nage  = 20\ngpa  = 9.5\nis_student = True',
        label: '👉 No type declaration needed in Python' },
      { type: 'explain', title: 'Dynamic typing',
        code: 'x = 5        # int\nx = "hello"  # now a string!\ntype(x)      # <class "str">',
        points: ['Python infers the type automatically',
                 'No int, String, etc. keywords needed',
                 'type() reveals the type',
                 'Variable can change type (dynamic typing)'] },
      { type: 'tap', question: '👉 Do you need to declare the type in Python?',
        options: [{ text: 'Yes, always',  correct: false },
                  { text: 'No',           correct: true  },
                  { text: 'Only for int', correct: false }] },
      { type: 'mcq', question: '👉 What is type(3.14)?',
        options: [{ text: "<class 'int'>",   correct: false },
                  { text: "<class 'float'>", correct: true  },
                  { text: "<class 'str'>",   correct: false },
                  { text: "number",          correct: false }] },
      { type: 'fill', title: 'Assign a boolean',
        blank: 'is_active = ___', answer: 'True' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create variables name, age, and height. Print all three on one line' }
    ]
  },
  {
    chapterNum: 3, title: 'Input', goal: 'Read user input in Python',
    icon: '⌨️', color: '#ffc800',
    steps: [
      { type: 'show', title: 'input() function',
        code: 'name = input("Enter your name: ")\nprint("Hello,", name)',
        label: '👉 input() always returns a string' },
      { type: 'explain', title: 'Converting input types',
        code: 'age  = int(input("Age: "))    # to int\ngpa  = float(input("GPA: "))  # to float\nname = input("Name: ")         # stays str',
        points: ['input() always returns a string',
                 'int() → converts string to integer',
                 'float() → converts to decimal',
                 'Without conversion: "5" + 3 = TypeError'] },
      { type: 'tap', question: '👉 What does input() always return?',
        options: [{ text: 'An integer', correct: false },
                  { text: 'A string',   correct: true  },
                  { text: 'A number',   correct: false }] },
      { type: 'mcq', question: '👉 How do you read an integer from user input?',
        options: [{ text: 'input(int)',      correct: false },
                  { text: 'int(input())',    correct: true  },
                  { text: 'scanf("%d")',     correct: false },
                  { text: 'nextInt()',       correct: false }] },
      { type: 'fill', title: 'Read integer input',
        blank: 'age = ___(input("Age: "))', answer: 'int' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read two numbers from input and print their sum (remember type conversion!)' }
    ]
  },
  {
    chapterNum: 4, title: 'If-Else', goal: 'Decision making in Python',
    icon: '🔀', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'If-else in Python',
        code: 'if score >= 50:\n    print("Pass")\nelse:\n    print("Fail")',
        label: '👉 Python uses indentation instead of { }' },
      { type: 'explain', title: 'Indentation is required',
        code: 'if x > 0:\n    print("Positive")  # 4 spaces!\nelif x == 0:\n    print("Zero")\nelse:\n    print("Negative")',
        points: ['No { } — Python uses indentation',
                 '4 spaces (or 1 tab) for each block',
                 'elif = else if',
                 'Colon : required after condition'] },
      { type: 'tap', question: '👉 What replaces { } in Python?',
        options: [{ text: 'Semicolons',  correct: false },
                  { text: 'Indentation', correct: true  },
                  { text: 'Parentheses', correct: false }] },
      { type: 'mcq', question: '👉 x = 0. What prints?',
        code: 'if x > 0:\n    print("Pos")\nelif x == 0:\n    print("Zero")\nelse:\n    print("Neg")',
        options: [{ text: 'Pos',   correct: false },
                  { text: 'Zero',  correct: true  },
                  { text: 'Neg',   correct: false },
                  { text: 'Error', correct: false }] },
      { type: 'fill', title: 'Complete the condition',
        blank: 'if age ___ 18:\n    print("Adult")', answer: '>=' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read a number and print "Even" or "Odd" using if-else and the % operator' }
    ]
  },
  {
    chapterNum: 5, title: 'Loops', goal: 'Repeat code in Python',
    icon: '🔄', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'For loop with range()',
        code: 'for i in range(5):\n    print(i)',
        label: '👉 range(5) = 0, 1, 2, 3, 4' },
      { type: 'explain', title: 'range() options',
        code: 'range(5)       # 0 to 4\nrange(1, 6)    # 1 to 5\nrange(0, 10, 2) # 0,2,4,6,8 (step 2)',
        points: ['range(stop) → 0 to stop-1',
                 'range(start, stop) → start to stop-1',
                 'range(start, stop, step) → with step',
                 'for x in list → iterate list items'] },
      { type: 'tap', question: '👉 What does range(3) produce?',
        options: [{ text: '1, 2, 3',    correct: false },
                  { text: '0, 1, 2',    correct: true  },
                  { text: '0, 1, 2, 3', correct: false }] },
      { type: 'mcq', question: '👉 Which loop iterates directly over a list?',
        code: 'fruits = ["apple", "mango"]',
        options: [{ text: 'for i in range(fruits)', correct: false },
                  { text: 'for f in fruits',        correct: true  },
                  { text: 'while fruits',           correct: false },
                  { text: 'foreach f in fruits',    correct: false }] },
      { type: 'fill', title: 'Loop 1 to 5',
        blank: 'for i in range(___, 6):', answer: '1' },
      { type: 'final', title: 'Final Challenge',
        task: 'Print the sum of all numbers from 1 to 100 using a loop' }
    ]
  },
  {
    chapterNum: 6, title: 'Functions', goal: 'Write functions in Python',
    icon: '⚙️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Functions in Python',
        code: 'def greet(name):\n    return "Hello, " + name\n\nprint(greet("Abhay"))',
        label: '👉 Use def keyword to create a function' },
      { type: 'explain', title: 'Default parameters',
        code: 'def greet(name="World"):\n    return "Hello, " + name\n\ngreet()         # "Hello, World"\ngreet("Abhay")  # "Hello, Abhay"',
        points: ['def → defines a function',
                 'Default values: def f(x=0)',
                 'return → sends value back',
                 'Functions without return → return None'] },
      { type: 'tap', question: '👉 Which keyword defines a function in Python?',
        options: [{ text: 'function', correct: false },
                  { text: 'def',      correct: true  },
                  { text: 'func',     correct: false }] },
      { type: 'mcq', question: '👉 What is returned if a function has no return?',
        options: [{ text: '0',    correct: false },
                  { text: 'None', correct: true  },
                  { text: '-1',   correct: false },
                  { text: 'Error',correct: false }] },
      { type: 'fill', title: 'Define a function',
        blank: '___ add(a, b):\n    return a + b', answer: 'def' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a function "power" that takes base and exponent, returns base**exponent' }
    ]
  },
  {
    chapterNum: 7, title: 'Lists', goal: 'Work with Python lists',
    icon: '📋', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Lists in Python',
        code: 'fruits = ["apple", "mango", "banana"]\nprint(fruits[0])  # apple\nprint(len(fruits)) # 3',
        label: '👉 Lists are like arrays but more powerful' },
      { type: 'explain', title: 'List methods',
        code: 'fruits.append("grape")   # add to end\nfruits.remove("mango")  # remove item\nfruits.sort()           # sort in place\nfruits[-1]              # last element',
        points: ['append() → add to end',
                 'remove() → remove by value',
                 'sort() → sort the list',
                 'fruits[-1] → last element (negative index)'] },
      { type: 'tap', question: '👉 What does append() do?',
        options: [{ text: 'Removes last element', correct: false },
                  { text: 'Adds to the end',      correct: true  },
                  { text: 'Sorts the list',        correct: false }] },
      { type: 'mcq', question: '👉 What is nums[-1]?',
        code: 'nums = [10, 20, 30, 40]',
        options: [{ text: '10', correct: false },
                  { text: '20', correct: false },
                  { text: '30', correct: false },
                  { text: '40', correct: true  }] },
      { type: 'fill', title: 'Add to list',
        blank: 'nums.___(100)', answer: 'append' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a list of 5 numbers, sort it, and print the first and last element' }
    ]
  },
  {
    chapterNum: 8, title: 'Dictionaries', goal: 'Use Python dicts',
    icon: '📚', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Dictionaries in Python',
        code: 'person = {\n    "name": "Abhay",\n    "age": 20\n}\nprint(person["name"])  # Abhay',
        label: '👉 Dict stores key-value pairs (like JSON)' },
      { type: 'explain', title: 'Dict operations',
        code: 'person["email"] = "a@b.com"  # add key\ndel person["age"]            # delete key\n"name" in person             # True\nlist(person.keys())          # all keys',
        points: ['Access: dict["key"]',
                 'Add: dict["newkey"] = value',
                 'Delete: del dict["key"]',
                 '"key" in dict → check existence'] },
      { type: 'tap', question: '👉 How do you access a dict value by key?',
        options: [{ text: 'dict.key',   correct: false },
                  { text: 'dict["key"]', correct: true  },
                  { text: 'dict[0]',    correct: false }] },
      { type: 'mcq', question: '👉 What does .keys() return?',
        options: [{ text: 'All values',       correct: false },
                  { text: 'All keys',         correct: true  },
                  { text: 'All key-value pairs', correct: false },
                  { text: 'The dict size',    correct: false }] },
      { type: 'fill', title: 'Add a key',
        blank: 'person[___] = "student"', answer: '"role"' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a dict for a student with name, age, grade. Print each value using .values()' }
    ]
  },
  {
    chapterNum: 9, title: 'String Methods', goal: 'Manipulate strings in Python',
    icon: '🔤', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Useful string methods',
        code: 'text = "Hello World"\ntext.upper()      # "HELLO WORLD"\ntext.lower()      # "hello world"\ntext.split()      # ["Hello", "World"]',
        label: '👉 Strings have many built-in methods' },
      { type: 'explain', title: 'More string operations',
        code: '"hello".replace("l", "r")  # "herro"\n"  hi  ".strip()           # "hi"\nf"Age: {20}"               # f-string',
        points: ['replace(old, new) → replace text',
                 'strip() → remove surrounding whitespace',
                 'f"text {var}" → f-string interpolation',
                 'len(text) → length of string'] },
      { type: 'tap', question: '👉 How do you make a string uppercase?',
        options: [{ text: 'text.toUpper()', correct: false },
                  { text: 'text.upper()',   correct: true  },
                  { text: 'upper(text)',    correct: false }] },
      { type: 'mcq', question: '👉 What does "hello world".split() return?',
        options: [{ text: '"hello", "world"',     correct: false },
                  { text: '["hello", "world"]',   correct: true  },
                  { text: '["h","e","l","l","o"]', correct: false },
                  { text: 'Error',                correct: false }] },
      { type: 'fill', title: 'Complete the f-string',
        blank: 'name = "Abhay"\nprint(f"Hello {___}")', answer: 'name' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read a sentence, print it reversed, uppercased, and count how many words it has' }
    ]
  },
  {
    chapterNum: 10, title: 'Classes', goal: 'OOP in Python',
    icon: '🏛️', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Classes in Python',
        code: 'class Car:\n    def __init__(self, brand):\n        self.brand = brand\n\n    def drive(self):\n        print("Driving", self.brand)',
        label: '👉 __init__ is the constructor' },
      { type: 'explain', title: 'self and inheritance',
        code: 'class ElectricCar(Car):\n    def charge(self):\n        print("Charging")\n\ne = ElectricCar("Tesla")\ne.drive()   # inherited\ne.charge()  # own method',
        points: ['self → refers to current object (like this)',
                 '__init__ → called when object created',
                 '(Car) → inherit from Car class',
                 'self.brand → instance variable'] },
      { type: 'tap', question: '👉 What is self in Python?',
        options: [{ text: 'The class itself',       correct: false },
                  { text: 'The current object instance', correct: true  },
                  { text: 'A keyword for static methods', correct: false }] },
      { type: 'mcq', question: '👉 What is the constructor called in Python?',
        options: [{ text: 'constructor()', correct: false },
                  { text: '__init__()',    correct: true  },
                  { text: 'new()',         correct: false },
                  { text: 'init()',        correct: false }] },
      { type: 'fill', title: 'Complete the constructor',
        blank: 'def ___(self, name):\n    self.name = name', answer: '__init__' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a BankAccount class with balance, deposit(), and withdraw() methods' }
    ]
  }
];

// ── C# / .NET (course_id = 4) ────────────────────────────────────────────────
export const CSHARP_CHAPTERS: Chapter[] = [
  {
    chapterNum: 1, title: 'Output', goal: 'Print output in C#',
    icon: '🖨️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Printing in C#',
        code: 'Console.WriteLine("Hello World");', label: '👉 Console.WriteLine prints and adds newline' },
      { type: 'explain', title: 'Console methods',
        code: 'Console.WriteLine("Hello"); // with newline\nConsole.Write("Hi ");       // no newline\nConsole.WriteLine(5 + 3);   // prints 8',
        points: ['Console.WriteLine → print + newline',
                 'Console.Write → print without newline',
                 'Part of System namespace',
                 'Can print numbers, strings, expressions'] },
      { type: 'tap', question: '👉 Which adds a newline after printing?',
        options: [{ text: 'Console.Write()',     correct: false },
                  { text: 'Console.WriteLine()', correct: true  },
                  { text: 'Console.Print()',      correct: false }] },
      { type: 'mcq', question: '👉 What is the output?',
        code: 'Console.WriteLine("C#");',
        options: [{ text: 'Console', correct: false },
                  { text: 'C#',      correct: true  },
                  { text: 'WriteLine',correct: false },
                  { text: 'Error',    correct: false }] },
      { type: 'fill', title: 'Complete the print',
        blank: 'Console.___("Hello");', answer: 'WriteLine' },
      { type: 'error_fix', question: '👉 What is wrong?',
        brokenCode: 'console.writeline("Hello");',
        options: [{ text: 'C# is case-sensitive: Console.WriteLine', correct: true  },
                  { text: 'Missing semicolon',                        correct: false },
                  { text: 'Nothing is wrong',                         correct: false }] },
      { type: 'final', title: 'Final Challenge',
        task: 'Print "Hello from C#!" using the correct C# syntax' }
    ]
  },
  {
    chapterNum: 2, title: 'Variables & Types', goal: 'Declare variables in C#',
    icon: '📦', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Variables in C#',
        code: 'int age     = 20;\nstring name = "Abhay";\ndouble gpa  = 9.5;\nbool pass   = true;',
        label: '👉 C# is strongly typed like Java' },
      { type: 'explain', title: 'var keyword',
        code: 'var age  = 20;      // inferred as int\nvar name = "Abhay"; // inferred as string\nvar pi   = 3.14;    // inferred as double',
        points: ['var → compiler infers the type',
                 'string with lowercase s (unlike Java)',
                 'int, double, bool, char same as Java',
                 'Once assigned, var type cannot change'] },
      { type: 'tap', question: '👉 How is string different in C# vs Java?',
        options: [{ text: 'C# uses string (lowercase s)', correct: true  },
                  { text: 'C# uses String (uppercase S)', correct: false },
                  { text: 'No difference',                correct: false }] },
      { type: 'mcq', question: '👉 What type does var infer for: var x = 3.14?',
        options: [{ text: 'int',    correct: false },
                  { text: 'float',  correct: false },
                  { text: 'double', correct: true  },
                  { text: 'var',    correct: false }] },
      { type: 'fill', title: 'Use var',
        blank: '___ score = 95;', answer: 'var' },
      { type: 'final', title: 'Final Challenge',
        task: 'Declare name (string), age (int), and isStudent (bool) and print all three' }
    ]
  },
  {
    chapterNum: 3, title: 'Input', goal: 'Read user input in C#',
    icon: '⌨️', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Reading input in C#',
        code: 'string name = Console.ReadLine();\nint age = int.Parse(Console.ReadLine());',
        label: '👉 ReadLine() reads a line, returns string' },
      { type: 'explain', title: 'Type conversion',
        code: 'int.Parse("42")       // string → int\ndouble.Parse("3.14")  // string → double\nConvert.ToInt32("42") // alternative',
        points: ['Console.ReadLine() → always returns string',
                 'int.Parse() → convert string to int',
                 'double.Parse() → convert to double',
                 'Convert.ToInt32() → safer alternative'] },
      { type: 'tap', question: '👉 What does Console.ReadLine() return?',
        options: [{ text: 'An int',    correct: false },
                  { text: 'A string',  correct: true  },
                  { text: 'A double',  correct: false }] },
      { type: 'mcq', question: '👉 How do you convert "5" to int in C#?',
        options: [{ text: 'int("5")',        correct: false },
                  { text: 'int.Parse("5")',  correct: true  },
                  { text: '(int)"5"',        correct: false },
                  { text: 'parseInt("5")',   correct: false }] },
      { type: 'fill', title: 'Parse integer input',
        blank: 'int n = int.___( Console.ReadLine() );', answer: 'Parse' },
      { type: 'final', title: 'Final Challenge',
        task: 'Read a number from user and print its square using Console.WriteLine' }
    ]
  },
  {
    chapterNum: 4, title: 'If-Else', goal: 'Decision making in C#',
    icon: '🔀', color: '#ffc800',
    steps: [
      { type: 'show', title: 'If-else in C#',
        code: 'if (score >= 50)\n    Console.WriteLine("Pass");\nelse\n    Console.WriteLine("Fail");',
        label: '👉 Same structure as Java and C' },
      { type: 'explain', title: 'Ternary operator',
        code: 'string result = score >= 50 ? "Pass" : "Fail";\nConsole.WriteLine(result);',
        points: ['condition ? trueValue : falseValue',
                 'Ternary is shorthand for if-else',
                 'Good for simple assignments',
                 'Avoid nesting ternaries (hard to read)'] },
      { type: 'tap', question: '👉 What is the ternary operator symbol?',
        options: [{ text: '??',  correct: false },
                  { text: '? :', correct: true  },
                  { text: '::',  correct: false }] },
      { type: 'mcq', question: '👉 x = 7. What is result?',
        code: 'var result = x > 5 ? "Big" : "Small";',
        options: [{ text: 'Small', correct: false },
                  { text: 'Big',   correct: true  },
                  { text: 'x',     correct: false },
                  { text: 'Error', correct: false }] },
      { type: 'fill', title: 'Complete the ternary',
        blank: 'var msg = age >= 18 ___ "Adult" : "Minor";', answer: '?' },
      { type: 'final', title: 'Final Challenge',
        task: 'Use a ternary to check if a number is even or odd and print the result' }
    ]
  },
  {
    chapterNum: 5, title: 'Loops', goal: 'Repeat code in C#',
    icon: '🔄', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Loops in C#',
        code: 'for (int i = 1; i <= 5; i++)\n    Console.WriteLine(i);',
        label: '👉 Same for loop as C/Java' },
      { type: 'explain', title: 'foreach loop',
        code: 'int[] nums = {1, 2, 3, 4, 5};\nforeach (int n in nums)\n    Console.WriteLine(n);',
        points: ['foreach → iterate over collections',
                 'foreach (type item in collection)',
                 'Cleaner than for loop for collections',
                 'Cannot modify collection while iterating'] },
      { type: 'tap', question: '👉 Which loop is best for iterating an array in C#?',
        options: [{ text: 'while',   correct: false },
                  { text: 'foreach', correct: true  },
                  { text: 'do-while',correct: false }] },
      { type: 'mcq', question: '👉 What does foreach need?',
        options: [{ text: 'An index',         correct: false },
                  { text: 'A collection/array', correct: true  },
                  { text: 'A condition',        correct: false },
                  { text: 'A counter',          correct: false }] },
      { type: 'fill', title: 'Complete the foreach',
        blank: 'foreach (___ n in nums)', answer: 'int' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create an int array of 5 values, use foreach to find and print the maximum' }
    ]
  },
  {
    chapterNum: 6, title: 'Methods', goal: 'Write methods in C#',
    icon: '⚙️', color: '#ff6b6b',
    steps: [
      { type: 'show', title: 'Methods in C#',
        code: 'static int Add(int a, int b)\n{\n    return a + b;\n}',
        label: '👉 Methods in C# start with capital letter (convention)' },
      { type: 'explain', title: 'Method overloading',
        code: 'static int Add(int a, int b)    { return a+b; }\nstatic double Add(double a, double b) { return a+b; }',
        points: ['Same method name, different parameter types',
                 'Compiler picks the right version',
                 'C# methods use PascalCase (MethodName)',
                 'static → call without object'] },
      { type: 'tap', question: '👉 What is method overloading?',
        options: [{ text: 'Two classes with same name',         correct: false },
                  { text: 'Same method name, different params', correct: true  },
                  { text: 'Calling a method twice',             correct: false }] },
      { type: 'mcq', question: '👉 What naming convention do C# methods use?',
        options: [{ text: 'camelCase',  correct: false },
                  { text: 'snake_case', correct: false },
                  { text: 'PascalCase', correct: true  },
                  { text: 'UPPER_CASE', correct: false }] },
      { type: 'fill', title: 'Declare a method',
        blank: 'static ___ Greet() { Console.WriteLine("Hi"); }', answer: 'void' },
      { type: 'final', title: 'Final Challenge',
        task: 'Write a method Max(int a, int b) that returns the larger number' }
    ]
  },
  {
    chapterNum: 7, title: 'Classes & Objects', goal: 'OOP in C#',
    icon: '🏛️', color: '#7B68EE',
    steps: [
      { type: 'show', title: 'Classes in C#',
        code: 'class Car\n{\n    public string Brand;\n    public int Speed;\n\n    public void Drive()\n    {\n        Console.WriteLine("Driving " + Brand);\n    }\n}',
        label: '👉 Similar to Java but with different conventions' },
      { type: 'explain', title: 'Properties in C#',
        code: 'class Person\n{\n    public string Name { get; set; }\n    public int Age  { get; set; }\n}',
        points: ['{ get; set; } → auto-property (C# feature)',
                 'Properties replace public fields in real code',
                 'new Car() → creates object',
                 'car.Brand → access with dot'] },
      { type: 'tap', question: '👉 What does { get; set; } create?',
        options: [{ text: 'A method',    correct: false },
                  { text: 'A property',  correct: true  },
                  { text: 'A constructor', correct: false }] },
      { type: 'mcq', question: '👉 How to create a Car object in C#?',
        options: [{ text: 'Car c = Car()',     correct: false },
                  { text: 'Car c = new Car()', correct: true  },
                  { text: 'new Car c',          correct: false },
                  { text: 'create Car c',       correct: false }] },
      { type: 'fill', title: 'Create an object',
        blank: 'Person p = ___ Person();', answer: 'new' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a Student class with Name and Grade properties, then instantiate and print them' }
    ]
  },
  {
    chapterNum: 8, title: 'Arrays & Lists', goal: 'Collections in C#',
    icon: '📋', color: '#04e88d',
    steps: [
      { type: 'show', title: 'Array and List in C#',
        code: 'int[] arr = {1, 2, 3};\nList<int> list = new List<int> {1, 2, 3};',
        label: '👉 List<T> is more flexible than arrays' },
      { type: 'explain', title: 'List methods',
        code: 'list.Add(4);         // add element\nlist.Remove(2);      // remove value\nlist.Count;          // number of items\nlist.Contains(3);    // true/false',
        points: ['Add() → add to end of list',
                 'Remove() → remove by value',
                 'Count → number of items (not Length)',
                 'Contains() → check if item exists'] },
      { type: 'tap', question: '👉 How do you get list size in C#?',
        options: [{ text: 'list.Length',  correct: false },
                  { text: 'list.Count',   correct: true  },
                  { text: 'list.Size()',  correct: false }] },
      { type: 'mcq', question: '👉 What is the type for a list of strings in C#?',
        options: [{ text: 'List<string>',  correct: true  },
                  { text: 'List(string)',  correct: false },
                  { text: 'string[]',      correct: false },
                  { text: 'ArrayList',     correct: false }] },
      { type: 'fill', title: 'Add to list',
        blank: 'names.___(\"Alice\");', answer: 'Add' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a List<string> of 3 cities, add one more, then print all using foreach' }
    ]
  },
  {
    chapterNum: 9, title: 'Inheritance', goal: 'Extend classes in C#',
    icon: '🧬', color: '#ffc800',
    steps: [
      { type: 'show', title: 'Inheritance in C#',
        code: 'class Animal\n{\n    public void Eat() { Console.WriteLine("Eating"); }\n}\n\nclass Dog : Animal\n{\n    public void Bark() { Console.WriteLine("Woof!"); }\n}',
        label: '👉 : Animal = inherit from Animal' },
      { type: 'explain', title: 'virtual and override',
        code: 'class Animal {\n    public virtual void Speak() { ... }\n}\nclass Dog : Animal {\n    public override void Speak() { ... }\n}',
        points: ['virtual → method can be overridden',
                 'override → replacing parent method',
                 ': ClassName → inherit in C#',
                 'base.Method() → call parent method'] },
      { type: 'tap', question: '👉 Which keyword allows overriding in C#?',
        options: [{ text: 'abstract', correct: false },
                  { text: 'virtual',  correct: true  },
                  { text: 'static',   correct: false }] },
      { type: 'mcq', question: '👉 Syntax for C# inheritance?',
        options: [{ text: 'class Dog extends Animal',  correct: false },
                  { text: 'class Dog : Animal',        correct: true  },
                  { text: 'class Dog implements Animal',correct: false },
                  { text: 'Dog inherits Animal',        correct: false }] },
      { type: 'fill', title: 'Complete the override',
        blank: 'public ___ void Speak() { }', answer: 'override' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create Vehicle with virtual Move(), then Car class that overrides Move() with different output' }
    ]
  },
  {
    chapterNum: 10, title: 'Interfaces & LINQ', goal: 'Advanced C# features',
    icon: '🔌', color: '#61DAFB',
    steps: [
      { type: 'show', title: 'Interfaces in C#',
        code: 'interface IDrawable\n{\n    void Draw();\n}\n\nclass Circle : IDrawable\n{\n    public void Draw() { Console.WriteLine("○"); }\n}',
        label: '👉 Interfaces define contracts — I prefix by convention' },
      { type: 'explain', title: 'LINQ basics',
        code: 'int[] nums = {1,2,3,4,5,6};\nvar evens = nums.Where(n => n % 2 == 0);\nforeach(var n in evens)\n    Console.WriteLine(n);',
        points: ['LINQ = Language Integrated Query',
                 'Where() → filter (like SQL WHERE)',
                 'Select() → transform (like SQL SELECT)',
                 'Lambda n => n % 2 == 0 → filter condition'] },
      { type: 'tap', question: '👉 What does LINQ Where() do?',
        options: [{ text: 'Sorts items',          correct: false },
                  { text: 'Filters items',        correct: true  },
                  { text: 'Transforms each item', correct: false }] },
      { type: 'mcq', question: '👉 Interface naming convention in C#?',
        options: [{ text: 'Starts with A',  correct: false },
                  { text: 'Starts with I',  correct: true  },
                  { text: 'Ends with Impl', correct: false },
                  { text: 'No convention',  correct: false }] },
      { type: 'fill', title: 'Complete the LINQ filter',
        blank: 'var big = nums.___(n => n > 10);', answer: 'Where' },
      { type: 'final', title: 'Final Challenge',
        task: 'Create a List<int> of 10 numbers. Use LINQ to filter only those > 5 and print them' }
    ]
  }
];

// ── Chapter map by course_id ─────────────────────────────────────────────────
export const CHAPTERS_BY_COURSE: Record<number, Chapter[]> = {
  1: C_CHAPTERS,
  2: CPP_CHAPTERS,
  3: JAVA_CHAPTERS,
  4: CSHARP_CHAPTERS,
  5: JS_CHAPTERS,
  6: PYTHON_CHAPTERS,
};
